=  Contracts

OpenNautilus Contracts is an open-source library for smart contract development.

* It focuses on zero-knowledge applications (zkApps).
* Provides tools and abstractions for simplified development process.
* Allows developers to focus on core logic, removing low-level complexities.

== Overview

=== Installation

[source,sh]
----
npm i @zkoracle/opennuatilus-contracts --save
----

=== Usage

After the installation, you can utilize the contracts present in the library by performing an import operation:

[source,typescript]
----
import {
  IERC20,
  buildERC20Contract
} from '@zkoracle/opennautilus-contracts';

let zkAppPrivateKey = PrivateKey.random();
let zkAppAddress = zkAppPrivateKey.toPublicKey();

let zkApp: SmartContract & IERC20;

zkApp = await buildERC20Contract(zkAppAddress, 'SomeCoin', "SOM", 9);

----

== Security

Our software is currently undergoing a security audit. It's a process to identify potential vulnerabilities in the code.
Although we aim for utmost security, all software carries some risk. While our audit is still in progress, users are responsible for assessing their risk before using the software.

We disclaim any liability for potential damages during this period. Updates will be provided as we progress.

== Learn More
TBD
